FORMAT: 1A
HOST: https://bortolotti-luglio-calcio.herokuapp.com/

# Mondiali calcio

é una semplice api che permette di avere informazioni sulle squadre di calcio presenti al mondiale 2018

## Questions Collection [/team?name=]

### List All Questions [GET]

restituisce le info su una squadra

+ Response 200 (application/json)
       
        {
            "name": "Croazia",
            "is_still_in": "true"
            "matches": [
                "belgio, w",
                "islanda, d",
                "argentina, l"
                ]
            
        }
        


### Create a New Question [POST]

Puoi inserire o modificare le informazioni su una squadra

+ Request (application/json)

        {
            "name": "Croazia",
            "matches": [
                "belgio, w",
                "islanda, d",
                "argentina, l"
                
            ]
            
        }

+ Response 201 (application/json)

    + Headers

            Location: /team?name=Croazia

    + Body

            {
            "name": "Croazia",
            "matches": [
                "belgio, w",
                "islanda, d",
                "argentina, l"
                
            ]
        
        
            }